cookie:
  expiry_days: 30
  key: huycuong03
  name: fordeer_cookie
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: 
      logged_in: False
      password: admin
      roles:
      - admin
      - editor
      - viewer